-- Smart mass replace using current search register
-- vim.keymap.set("n", "<leader>r", function()
--   -- Get what you just searched for in fzf-lua or via '/'
--   local search_term = vim.fn.getreg('/')
--
--   -- If search is empty, don't do anything to avoid errors
--   if search_term == "" then
--     print("Search register is empty!")
--     return
--   end
--
--   -- Construct command: :cfdo %s/old/|/gc | update
--   local cmd = ":cfdo %s/" .. search_term .. "//gc | update"
--
--   -- Place cursor right between // to type the replacement
--   local keys = vim.api.nvim_replace_termcodes(cmd .. string.rep("<Left>", 11), true, false, true)
--   vim.api.nvim_feedkeys(keys, "n", false)
-- end, { buffer = true, desc = "Smart replace from search" })

-- Bonus: quick way to close quickfix with 'q'
vim.keymap.set("n", "q", "<cmd>cclose<cr>", { buffer = true, silent = true })
